language: c
compiler: gcc
sudo: required
before_install:
    - sudo apt-get -qq update
    - sudo apt-get install automake autotools-dev diffutils help2man gawk
    - . ./.travis_before_install.sh
install: true
before_script: touch dumpfile.txt
script: autoreconf -iv && ./configure && make && sudo make install
after_success:
    - todo Test\ todo
    - todo -t 1
    - cat dumpfile.txt
