language: c
compiler: gcc
sudo: required
before_install:
    - sudo apt-get -qq update
    - sudo apt-get install automake autotools-dev diffutils help2man gawk
    - . ./.travis_before_install.sh
install: true
before_script: touch dumpfile.txt
script: autoreconf -iv && ./configure CPP='-DDEBUG=1' && make && sudo make install
after_success:
    - todo Test\ todo
    - todo -t 0
    - todo This\ one\ is\ done. -y
    - todo Proper\ Unicode\ Support\ 😂
    - todo -t 2
    - todo -1
    - cat dumpfile.txt
